name: still daily run

on:
  workflow_dispatch:

jobs:
  build_and_excute:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Install rust run default
        run: rustup update stable && rustup default stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspace: ". -> target"

      - name: run
        run: |
          RANDOM_SEC=$((RANDOM % 14400))

          TIME="$(TZ="Asia/Shanghai" date -d "-$RANDOM_SEC seconds" +"%Y-%m-%d %H:%M:%S")"

          cd cli
          cargo run --release -- \
            -u "${{ secrets.ACCOUNT }}" \
            -p "${{ secrets.PASSWORD }}" \
            -m 2 \
            -r ./assets/map.geojson \
            -t "$TIME"
        env:
          BACKEND: ${{ secrets.BACKEND }}
